name: Deploy API Document on GitHub Pages

on:
  push:
    branches: [main, v1-main, v2-main, deploy-api-reference]

env:
  NODE_VERSION: '16'
  V3_DIR: 'v3'
  V2_DIR: 'v2'
  V1_DIR: 'v1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout (v3)
        uses: actions/checkout@v3
        with:
          ref: main
          path: ${{ env.V3_DIR }}
      - name: Install and Build (v3)
        working-directory: ${{ env.V3_DIR }}
        run: |
          npm ci
          npm run doc
      - name: Checkout (v2)
        uses: actions/checkout@v3
        with:
          ref: v2-master
          path: ${{ env.V2_DIR }}
      - name: Install and Build (v2)
        working-directory: ${{ env.V2_DIR }}
        run: |
          npm ci
          npm run doc
      - name: Checkout (v1)
        uses: actions/checkout@v3
        with:
          ref: v1-master
          path: ${{ env.V1_DIR }}
      - name: Install and Build (v1)
        working-directory: ${{ env.V1_DIR }}
        run: |
          npm install
          npm run doc
      - name: Copy reference docs
        run: |
          mkdir -p public
          cp -r ${{ env.V3_DIR }}/doc/html/ public/${{ env.V3_DIR }}/
          cp -r ${{ env.V2_DIR }}/doc/html/ public/${{ env.V2_DIR }}/
          cp -r ${{ env.V1_DIR }}/doc/html/ public/${{ env.V1_DIR }}/
      - name: Deploy on gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
